### ISSUE TITLE
[improvement] add geoloc to referential INSEE

### ISSUE THREAD

**Issue by phileas-condemine** [eig-2017/the-magical-csv-merge-machine#100]
geocoded SIRENE can be found on C. QUEST website : http://data.cquest.org/geo_sirene/
long-lat could be very helpful for "fuzzy" merging.

**Comment by Leobouloc** [comment]
Thank you for your feedback. Currently, the merge machine interprets all data as strings and therefore latlong comparisons could only really be useful in the case of an exact match, which seems like an unlikely use case. But we will keep  this in mind if the core matching algorithm evolves.
